### PR TITLE
Enhanced tools build

### PR DESCRIPTION
**Pull request by ghaerr**
While this PR seems large, it is mostly a refactoring of Makefiles, and then a rename of ndisasm/ -> nasm32/.

The main enhancement is to cleanup the build process so that it only rebuilds the tools that have changes to the source files, rather than recompiling and relinking all the tools every time. This means that the tree isn't cleaned every time, except if just "make" is run, in which the effect is the same as before.

The enhanced build allows for much quicker development of the tools, which is going to be necessary to make changes for compiling the ELKS C library, for instance. Since there is an ongoing problem with the same named .o files being produced for ELKS and host, but being incompatible, the following approach can now be used for speed:
```
# to build host versions:
make clean
make host
... (edit files)
make host
...etc and repeat

# to build ELKS versions:
make clean
make elks
... (edit files)
make elks
...etc and repeat

# to build everything, but clean everything, starting from scratch:
make
```

Other changes are:
- Adds -stackcheck= option to C86 (default =no)
- Adds C86 and LD86 man pages (usage `eman compiler/c86.1` or `eman ld/ld86.1` for now. (`eman` is in the ELKS tools/bin dir)
- cpp is renamed cpp86, so as to not conflict with any host cpp by the same name
- Removes objdump86 (from the dev86/ld sources) from the build, as it is buggy and won't work with nasm produced as86 format .o files. The host version of the same name in tools/bin should be used. I will port a version of this over for ELKS when needed.
- Builds smaller 8086 ndisasm from nasm/ directory, rather than ndisasm/ directory. This will allow for a much smaller ndisasm on ELKS by default.
- The larger nasm and ndisasm, capable of all 32-bit assembly and disassembly, is built in nasm32/, which is ndisasm/ renamed to nasm32/. If wanted, those host programs can be used from that directory. Note of course that ELKS nasm32 can't be built, since it is way too large.

### CODE REVIEW

**Comment by ghaerr** [comment]
A further change that I think would be a good idea (in a future PR) would be to rename nasm to nasm86, so that nasm doesn't interfere with any host-based nasm of the same name. This would also give the result that all the 8086 toolchain programs would end in \*86, except for `make`. Perhaps make should also be renamed make86, at least for the host build, since otherwise it can't be easily tested, since it is the same name as the host make.

I also think that assembler/ should be renamed nasm86/. 

Would it be OK for me to post these changes in a separate PR?

**Comment by rafael2k** [comment]
Hi @ghaerr ! Thanks, and sure - as you prefer!
Btw, ndisasm from nasm86 is broken, I did something which broke it, and I never "unbroke" it again.

**Comment by ghaerr** [comment]
> ndisasm from nasm86 is broken, I did something which broke it, and I never "unbroke" it again.

Oh, I didn't know that. Let me check into it...

**Comment by ghaerr** [comment]
> ndisasm from nasm86 is broken, I did something which broke it, and I never "unbroke" it again.

Can you give a description of what is broken, I forgot to ask.

**Comment by rafael2k** [comment]
I dumps incorrect output, with lots of "db"

**Pull request merged**
