### PR TITLE
Add disasm86 to ELKS build, decrease size of executables

### PR DESCRIPTION
**Pull request by ghaerr**
Compiler optimization increased to -O3 for host build.

Changed some options that decrease size of ld86 and nasm for ELKS build.
Split syscall.asm into two to decrease size of most ELKS executables for now.

Add disasm86 to ELKS build, able to disassemble linked executables with symbols!
Add objdump86 to ELKS build.

Enhanced ld86 to pad the .text section with NOPs rather than NULs so disasm86 (or humans) don't desync when displaying instruction stream.

Introduced disasm/Makefile.elks as small sample makefile for IA16 compiler. Will do same for OWCC. This should allow Makefiles to be combined in the future, rather than maintaining multiple Makefiles per directory.

Converted cpp/Makefile.elks into small sample makefile for OWC compiler. This can be used as a template for other OWCC programs. In the future, the use of watcom.inc with the standardized section could be done to greatly reduce Makefile complexity.

Converted cpp/Makefile into small sample makefile for host compiler. This resulted in a number of warnings appearing, since CFLAGS wasn't actually getting used in compilation due to broken Makefile rules. Corrected various warnings.

Cleaned up make/Makefile. Renamed host 'make' to 'make86' to allow testing. 

Tested ELKS make using compile, assemble, link, objdump86 and disasm86, everything working.

### CODE REVIEW

**Comment by ghaerr** [comment]
BTW, rather than including hard paths in Makefiles, seemingly to set TOPDIR, I use the following alias in my .bashrc file in order to set the PATH and TOPDIR to work with the IA16 compiler and/or ELKS:
```
alias ee='cd ~greg/net/elks-gh; . env.sh'
```
Then just type `ee` with any new terminal shell and done. Of course, the alias needs to be edited to your location.

For Open Watcom, I have the same sort of thing:
```
alias ow='cd  ~greg/net/elks-gh/libc; . wcenv.sh'  # wcenv.sh may need to be edited if running on Linux, or put somewhere else
```

IMO, this is better than including hard paths in Makefiles. In the sample disasm/Makefile.elks in this PR, a check for whether TOPDIR is defined or not and an error given, rather than continuing without, but it doesn't try to guess a path to the ELKS installation.

**Comment by ghaerr** [comment]
The original problem of running `./cpp86 -D__C86__ -D__STDC__` started failing again on my system. I checked the CPP86 source and found there were a number of malloc allocations without any checking for NULL pointer. Add checking and error message in each case.

Afterwards, the problem went away - without failing. So there's something fishy going on, we may need more more memory, or something else may be buggy. When the problem occurred, CPP86 outputs the .i file to stdout, which is definitely incorrect, and then nasm hangs. So I'm pretty sure the problem is in CPP86. It's back to working again on my system with -D arguments, we'll see how things go.

**Comment by ghaerr** [comment]
Hello @rafael2k,

This PR got a little bigger than I intended, sorry. After building some "standardized" Makefiles for host and ELKS builds, I started playing around with ar/ and make/ directories and realized that CFLAGS and other variables weren't getting set as intended for the compilations. This resulted in more warnings that had to be fixed, once the Makefiles were updated. To make things easier, all the simpler utilities  (ar/, make/, cpp/ and disasm/) now use the template Makefile and Makefile.elks, which are much simpler to fill out and prove correct.

I've tested everything on host and ELKS, and things seem to be working well with no compilation warnings for the time being. I'll try to leave the repo alone for a while!

Thank you!

**Comment by rafael2k** [comment]
This is wonderful @ghaerr !
I'll test here too with my setup to check if it all runs fine too.

**Pull request merged**
